<html>
<head>
<title>""</title>
</head>
<body style="background-color:black;margin:50px;">
<div style="text-align:center;color:white;">
  <?php
  if(isset($_GET['answer']) && $_GET['answer'] =="aksjdkjalskdjalksjdkjasdqweuqowiehajshdjashoqiwheoqwhajhashfqweiqwoiehashdjkhjqwheoqiwhrqowhtrqowhaskjhfajhsfqwriuaovhn80912374189274y1723g1ji2h3jkbajksbd"){
echo "<h1>ZUUP BRUH!?! YOU DID IT BRUH!!</h1>";
echo "<br/>Level 2 <a href='GO2HELL.PHP'> GO2HELL.php</a>";
echo "<br/><img src='CURIOUS.png' alt='letter-C'>";
  }
  else {
    echo "<h1>ZUUP BRUH!?! <br/>ERROR BRUH!!! <br/>TRY AGAIN BRUH!!!<br/> BRUH!?!?!</h1>";
    echo "<pre>Want some hint?
    Try to light me up or just view the source
    ...
    <span style='color:black'>You can drag C on the url.</span></pre>";
  }
  ?>


</pre>
</div>
</body>
</html>
